services:
  mock-server:
    build:
      context: ./mock-server
      dockerfile: Dockerfile
    container_name: mock-server
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./mock-server/routes.json:/app/routes.json
      - ./mock-server/responses:/app/responses:ro
      - ./mock-server/static/swagger:/app/static/swagger

  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: http://mock-server:8080
    container_name: mock-ui
    depends_on:
      - mock-server
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://mock-server:8080
